// SPDX-FileCopyrightText: 2002-2025 PCSX2 Dev Team
// SPDX-License-Identifier: GPL-3.0+

#pragma once

#if defined(__APPLE__)
#include <TargetConditionals.h>

#ifndef TARGET_OS_MACCATALYST
#define TARGET_OS_MACCATALYST 0
#endif

#define ARMSX2_APPLE_IOS_SIMULATOR (TARGET_OS_SIMULATOR)
#define ARMSX2_APPLE_MAC_CATALYST (TARGET_OS_MACCATALYST)
#define ARMSX2_APPLE_IOS_DEVICE (TARGET_OS_IPHONE && !TARGET_OS_SIMULATOR && !TARGET_OS_MACCATALYST)
#define ARMSX2_APPLE_MACOS_NATIVE (TARGET_OS_MAC && !TARGET_OS_IPHONE)
#define ARMSX2_APPLE_MAC_RUNTIME (ARMSX2_APPLE_MAC_CATALYST || ARMSX2_APPLE_MACOS_NATIVE)
#define ARMSX2_APPLE_UIKIT (TARGET_OS_IPHONE || TARGET_OS_MACCATALYST)
#else
#define ARMSX2_APPLE_IOS_SIMULATOR 0
#define ARMSX2_APPLE_MAC_CATALYST 0
#define ARMSX2_APPLE_IOS_DEVICE 0
#define ARMSX2_APPLE_MACOS_NATIVE 0
#define ARMSX2_APPLE_MAC_RUNTIME 0
#define ARMSX2_APPLE_UIKIT 0
#endif
